# Generated by Django 5.2.7 on 2025-10-02 16:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ChargePoint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("name", models.CharField(max_length=32, unique=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ready", "Ready"),
                            ("charging", "Charging"),
                            ("waiting", "Waiting"),
                            ("error", "Error"),
                        ],
                        default="ready",
                        max_length=16,
                    ),
                ),
            ],
            options={
                "indexes": [models.Index(fields=["status"], name="chargepoint_status_idx")],
            },
        ),
        migrations.CreateModel(
            name="Connector",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("evse_number", models.CharField(max_length=32, unique=True)),
                (
                    "charge_point",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="connectors",
                        to="chargepoints.chargepoint",
                    ),
                ),
            ],
            options={
                "abstract": False,
                "indexes": [models.Index(fields=["deleted_at"], name="connector_del_idx")],
            },
        ),
    ]
